### ISSUE TITLE
Cask 'java8' is unavailable

### ISSUE THREAD

**Issue by dennisausbremen** [dennisausbremen/macOStrap#4]
Cask 'java8' is unavailable: Fix!

**Comment by dennisausbremen** [comment]
use brew tap homebrew/cask-versions to fix this issue

**Comment by aquintiliano** [comment]
didn't work for me

**Comment by achwedyk** [comment]
It looks like Java 8 is no longer available due to Oracle licensing.
See https://github.com/Homebrew/homebrew-cask-versions/issues/7253

The solution is to either:
- install it manually from https://www.oracle.com/technetwork/java/javase/downloads/index.html (you need an Oracle account for that though)
- or use alternative JDK e.g. `brew cask install homebrew/cask-versions/adoptopenjdk8`
